#!/bin/bash

case `date +%H` in
  0|1|2|4|5|7|8|10|11|13|14|16|17|19|20|22|23 )
    exit 0
    ;;
esac


cd $OPENSHIFT_DATA_DIR
. .bash_profile

current_time=$(date "+%Y.%m.%d-%H.%M.%S")
current_date=$(date "+%Y.%m.%d")
LOGINDEX=logs.html

( echo "TIMESTAMP: $current_time" && \
echo "========================" && \
echo "PULLING ALL REPOSITORIES" && \
echo "========================" && \
./pullAllRepos.sh && \
echo "PUSHING ALL REPOSITORIES" && \
echo "========================" && \
./pushAllRepos.sh ) \
  >> ${OPENSHIFT_REPO_DIR}wsgi/static/pullPush.$current_date.log 2>&1

cd ${OPENSHIFT_REPO_DIR}wsgi/static

for a in *.log; do

  if [ "$a" != "pullPush.$current_date.log" ]; then
    
    gzip $a
    
  fi

done



echo "<html>
<head><title>$LOGINDEX</title>
</head>
<body bgcolor='grey'>" > $LOGINDEX

for a in *.log.*; do
  
# creating links to the files
echo "<br><a href='$a'>$a</a>" >> $LOGINDEX

done

# creating end tags for HTML

echo "</body>
</html>" >> $LOGINDEX
